apiVersion: v2
name: ska-mid-itf-dpd
description: An umbrella Helm chart for deployment of the SDP Data Product Dashboard at the Mid ITF
type: application
version: 26.0.0-rc.1
appVersion: 26.0.0-rc.1
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  - name: ska-dataproduct-dashboard
    version: 0.10.0
    repository: https://artefact.skao.int/repository/helm-internal
