apiVersion: v2
name: ska-mid-cbf-engineering-console-cache
description: A Helm chart for deployment of a PVC for persisting the Engineering Console downloads at the Mid ITF
type: application
version: 29.4.1-map502
appVersion: 29.4.1-map502
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
