namespace: eda-grafana-connector
app: eda-grafana-connector
image:
  registry: registry.gitlab.com/ska-telescope/ska-mid
  image: ska-mid-eda-grafana-connector
  tag: 0.0.9-dev.cbe183697
  pullPolicy: IfNotPresent
vault:
  edaCredentials:
    secretName: vault-mid-itf-eda-credentials
    mount: mid-itf
    mountPath: production/eda
    user: eda_ro
service:
  type: LoadBalancer
  port: 5001
environment:
  CREDENTIALS_PATH: /secrets/eda-credentials
  EDA_USER: eda_ro
  EDA_HOST: "eda.ska-tango-archiver.svc.miditf.internal.skao.int"
  SOURCE_CLUSTER_DOMAIN: "miditf.internal.skao.int"
  ATTRIBUTE_CONTEXT_FILE: "/app/libhdbpp-grafana-connector/ArchivingDataSource/skao-attribute-context.yaml"
  EDA_DATABASE_NAME: itf_eda
startup:
  command: '"sh", "-c", "poetry run grafana-connector"'
