image:
  registry: registry.gitlab.com/ska-telescope/ska-mid
  image: ska-mid-eda-grafana-connector
  tag: 0.0.8-dev.ca4c96a5f
  pullPolicy: IfNotPresent
vault:
  edaCredentials:
    secretName: vault-mid-itf-eda-credentials
    mountPath: /secrets/eda-credentials
    user: eda_ro
environment:
  CREDENTIALS_PATH: /secrets/eda-credentials
  EDA_USER: eda_ro
  EDA_HOST: "eda.ska-tango-archiver.svc.miditf.internal.skao.int"
  SOURCE_CLUSTER_DOMAIN: "miditf.internal.skao.int"
  ATTRIBUTE_CONTEXT_FILE: "/app/libhdbpp-grafana-connector/ArchivingDataSource/skao-attribute-context.yaml"
startup:
  command: '"sh", "-c", "poetry run grafana-connector"'
