db: tango-databaseds.dish-lmc-ska100.svc.ska100.mid.internal.skao.int:10000
manager: mid-eda/cm/01
archiver: mid-eda/es/01

configuration:
- class: DishManager
  attributes:
    dishmode:
      code_push_event: true
