db: tango-databaseds.dish-lmc-ska063.svc.ska063.mid.internal.skao.int:10000
manager: mid-eda/cm/01
archiver: mid-eda/es/01

configuration:
- class: DishManager
  attributes:
    # achievedpointing:
    #   code_push_event: true
    # achievedtargetlock:
    #   code_push_event: true
    # actstaticoffsetvalueel:
    #   code_push_event: true
    # actstaticoffsetvaluexel:
    #   code_push_event: true
    attenuationpolh:
      code_push_event: true
    attenuationpolv:
      code_push_event: true
    azimuthoverwrap:
      code_push_event: true
    # b2capabilitystate:
    #   code_push_event: true
    band2pointingmodelparams:
      code_push_event: true
    band2samplerfrequency:
      code_push_event: true
    buildstate:
      code_push_event: true
    # capturing:
    #   code_push_event: true
    configuredband:
      code_push_event: true
    # configuretargetlock:
    #   code_push_event: true
    # desiredpointingaz:
    #   code_push_event: true
    # desiredpointingel:
    #   code_push_event: true
    dishmode:
      code_push_event: true
    # dsconnectionstate:
    #   code_push_event: true
    # dshmaxshorttermpower:
    #   code_push_event: true
    # dshpowercurtailment:
    #   code_push_event: true
    # frequencyresponse:
    #   code_push_event: true
    healthstate:
      code_push_event: true
    ignorespf:
      code_push_event: true
    ignorespfrx:
      code_push_event: true
    kvalue:
      code_push_event: true
    lastcommandedmode:
      code_push_event: true
    noisediodeconfig:
      code_push_event: true
    noisediodemode:
      code_push_event: true
    periodicnoisediodepars:
      code_push_event: true
    pointingbuffersize:
      code_push_event: true
    # pointingstate:
    #   code_push_event: true
    # polytrack:
    #   code_push_event: true
    # programtracktable:
    #   code_push_event: true
    # pseudorandomnoisediodepars:
    #   code_push_event: true
    # scanid:
    #   code_push_event: true
    spfconnectionstate:
      code_push_event: true
    spfrxconnectionstate:
      code_push_event: true
    # trackinterpolationmode:
    #   code_push_event: true
    # trackprogrammode:
    #   code_push_event: true
    tracktableloadmode:
      code_push_event: true
- class: DSManager
  attributes:
    achievedtargetlock:
      code_push_event: true
    actstaticoffsetvalueel:
      code_push_event: true
    actstaticoffsetvaluexel:
      code_push_event: true
    azimuthspeed:
      code_push_event: true
    band1pointingmodelparams:
      code_push_event: true
    band2pointingmodelparams:
      code_push_event: true
    band3pointingmodelparams:
      code_push_event: true
    band4pointingmodelparams:
      code_push_event: true
    buildstate:
      code_push_event: true
    configuretargetlock:
      code_push_event: true
    currentpointing:
      code_push_event: true
    dscstate:
      code_push_event: true
    elevationspeed:
      code_push_event: true
    healthstate:
      code_push_event: true
    indexerposition:
      code_push_event: true
    operatingmode:
      code_push_event: true
    pointing_status_totalpointcorr_az:
      code_push_event: true
    pointing_status_totalpointcorr_el:
      code_push_event: true
    pointingstate:
      code_push_event: true
    powerstate:
      code_push_event: true
    safety_status_autostowactive:
      code_push_event: true
    safety_status_axes_initfault:
      code_push_event: true
    safety_status_estopfi:
      code_push_event: true
    safety_status_estophhp:
      code_push_event: true
    safety_status_estopped:
      code_push_event: true
    safety_status_estopturnhead:
      code_push_event: true
    safety_status_hatchazbearing:
      code_push_event: true
    safety_status_hatchturnheadroof:
      code_push_event: true
    safety_status_interlockclearable:
      code_push_event: true
    safety_status_lim2_ccw_az:
      code_push_event: true
    safety_status_lim2_ccw_fi:
      code_push_event: true
    safety_status_lim2_cw_az:
      code_push_event: true
    safety_status_lim2_cw_fi:
      code_push_event: true
    safety_status_lim2_dn_el:
      code_push_event: true
    safety_status_lim2_up_el:
      code_push_event: true
    safety_status_safetylockout_az:
      code_push_event: true
    safety_status_safetylockout_el:
      code_push_event: true
    safety_status_safetylockout_fi:
      code_push_event: true
    safety_status_safetystate:
      code_push_event: true
    safety_status_sto_az:
      code_push_event: true
    safety_status_sto_el:
      code_push_event: true
    safety_status_sto_fi:
      code_push_event: true
    safety_status_stowpinstatus:
      code_push_event: true
    time_cds_status_utctoskaepochsec:
      code_push_event: true
    tracking_status_tr_obj_valid:
      code_push_event: true
    tracking_tablestatus_pts_interpolerror:
      code_push_event: true
    tracking_tablestatus_pts_tablealmostfull:
      code_push_event: true
    trackinterpolationmode:
      code_push_event: true
    trackprogrammode:
      code_push_event: true
- class: Spfc
  attributes:
    b2CryoMotorState:
      code_push_event: true
    b2CalSourcePowerState:
      code_push_event: true
    heCompressorPowerState:
      code_push_event: true
    b2LnaHPowerState:
      code_push_event: true
    b2LnaVPowerState:
      code_push_event: true
    b2Amp2HPowerState:
      code_push_event: true
    b2Amp2VPowerState:
      code_push_event: true
    b2OmtTemp:
      code_push_event: true
      archive_abs_change: 0.1
    b2CalSourceTemp:
      code_push_event: true
      archive_abs_change: 0.1
    b2LnaTemp:
      code_push_event: true
      archive_abs_change: 0.1
    b2ColdheadStage1Temp:
      code_push_event: true
      archive_abs_change: 0.1
    heCompMotorTemp:
      code_push_event: true
      archive_abs_change: 0.1
    heCompSupplyTemp:
      code_push_event: true
      archive_abs_change: 0.1
    heCompSupplyPressure:
      code_push_event: true
      archive_abs_change: 0.1
    heCompReturnPressure:
      code_push_event: true
      archive_abs_change: 0.1
    b2ManifoldPressure:
      code_push_event: true
      archive_abs_change: 0.1
    b2CryoPressure:
      code_push_event: true
      archive_abs_change: 0.1
    b2CryoMotorSpeed:
      code_push_event: true
      archive_abs_change: 1
- class: SkaMidSpfrxControllerDs
  attributes:
    operatingMode:
      code_push_event: True
    configuredBand:
      code_push_event: True
    b1CapabilityState:
      code_push_event: True
    b2CapabilityState:
      code_push_event: True
    b3CapabilityState:
      code_push_event: True
    rxs123SurgeArresterVoltage:
      polling_period: 0
      archive_abs_change: 0.001
      archive_period: 0
    rxs123OdlB12Supply33Voltage:
      polling_period: 0
      archive_abs_change: 0.001
      archive_period: 0
    rxs123OdlB3Supply33Voltage:
      polling_period: 0
      archive_abs_change: 0.001
      archive_period: 0
    rxs123OdlPowerSupply5Voltage:
      polling_period: 0
      archive_abs_change: 0.001
      archive_period: 0
    rxs123OdlPowerSupply12Voltage:
      polling_period: 0
      archive_abs_change: 0.001
      archive_period: 0
    rxs123OdlB12Supply25Voltage:
      polling_period: 0
      archive_abs_change: 0.001
      archive_period: 0
    rxs123OdlB3Supply25Voltage:
      polling_period: 0
      archive_abs_change: 0.001
      archive_period: 0
    rxs123ClkPowerLevelVoltage:
      polling_period: 0
      archive_abs_change: 0.001
      archive_period: 0
    rxs123OdlTemperature:
      polling_period: 0
      archive_abs_change: 0.001
      archive_period: 0
    rxs123ODLHumidity:
      polling_period: 0
      archive_abs_change: 0.001
      archive_period: 0
    b123ProcCntlWrAlignStatus:
      polling_period: 0
      archive_abs_change: 1
      archive_period: 0
    b123ProcCntlWrFifoOvf:
      polling_period: 0
      archive_abs_change: 1
      archive_period: 0
    dataStreamBandChangeStatus:
      polling_period: 0
      archive_abs_change: 1
      archive_period: 0
    dataStreamCurrentBand:
      polling_period: 0
      archive_abs_change: 1
      archive_period: 0
